[package]
name = "bl-soc"
version = "0.0.0"
authors = [
    "Mingrui Ma <m202271767@hust.edu.cn>",
    "Zeqing Qin <zeqing@hust.edu.cn>"
]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base-address = "0.0.0"
volatile-register = "0.2.1"
embedded-hal = "1.0.0-rc.1"
embedded-time = "0.12.1"
embedded-io = "0.6.0"
cfg-if = "1.0.0"
# For backward compatibility only. 
embedded-hal-027 ={ package = "embedded-hal" , version = "0.2.7" }
as-slice = "0.2.1"

[dev-dependencies]
memoffset = "0.9.0"

[workspace]
members = [
    "examples/gpio-demo",
    "examples/i2c-demo",
    "examples/jtag-demo",
    "examples/lz4d-demo",
    "examples/multicore-demo/mcu",
    "examples/multicore-demo/dsp",
    "examples/pwm-demo",
    "examples/uart-demo",
]

[features]
default = []
bl602 = ["glb-v1"]
bl616 = ["glb-v2"]
bl702 = ["glb-v1"]
bl808 = ["glb-v2"]
glb-v1 = []
glb-v2 = []
