[package]
name = "bl-rom-rt"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memoffset = "0.8.0"

[workspace]
members = [
    "macros",
    "examples/baremetal-bl808-d0",
    "examples/baremetal-bl808-m0",
]

[features]
bl808-m0 = []
bl808-d0 = []
bl808-lp = []
