[package]
name = "bl-rom-rt"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bl-rom-rt-macros = { path = "macros" }
crc = "3.0.1"

[dev-dependencies]
memoffset = "0.8.0"

[features]
bl808-m0 = []
bl808-d0 = []
bl808-lp = []

[workspace]
members = [
    "macros",
]
