[workspace]
members = [
    "bl-rom-rt",
    "bl-rom-rt/macros",
    "bouffalo-hal",
    "blri",
    "bl-rom-rt/examples/blinky-bl808",
    "bl-rom-rt/examples/blinky-bl616",
    "examples/multicore/multicore-demo/mcu",
    "examples/multicore/multicore-demo/dsp",
    "examples/peripherals/gpio-demo",
    "examples/peripherals/i2c-demo",
    "examples/peripherals/jtag-demo",
    "examples/peripherals/lz4d-demo",
    "examples/peripherals/pwm-demo",
    "examples/peripherals/spi-demo",
    "examples/peripherals/uart-demo",
    "examples/peripherals/sdcard-demo",
    "examples/peripherals/sdcard-gpt-demo",
]
resolver = "2"
